// Code generated by ent, DO NOT EDIT.

package ent

import (
	"Portfolio/ent/formdata"
	"Portfolio/ent/predicate"
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// FormDataQuery is the builder for querying FormData entities.
type FormDataQuery struct {
	config
	ctx        *QueryContext
	order      []formdata.OrderOption
	inters     []Interceptor
	predicates []predicate.FormData
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the FormDataQuery builder.
func (fdq *FormDataQuery) Where(ps ...predicate.FormData) *FormDataQuery {
	fdq.predicates = append(fdq.predicates, ps...)
	return fdq
}

// Limit the number of records to be returned by this query.
func (fdq *FormDataQuery) Limit(limit int) *FormDataQuery {
	fdq.ctx.Limit = &limit
	return fdq
}

// Offset to start from.
func (fdq *FormDataQuery) Offset(offset int) *FormDataQuery {
	fdq.ctx.Offset = &offset
	return fdq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (fdq *FormDataQuery) Unique(unique bool) *FormDataQuery {
	fdq.ctx.Unique = &unique
	return fdq
}

// Order specifies how the records should be ordered.
func (fdq *FormDataQuery) Order(o ...formdata.OrderOption) *FormDataQuery {
	fdq.order = append(fdq.order, o...)
	return fdq
}

// First returns the first FormData entity from the query.
// Returns a *NotFoundError when no FormData was found.
func (fdq *FormDataQuery) First(ctx context.Context) (*FormData, error) {
	nodes, err := fdq.Limit(1).All(setContextOp(ctx, fdq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{formdata.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (fdq *FormDataQuery) FirstX(ctx context.Context) *FormData {
	node, err := fdq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first FormData ID from the query.
// Returns a *NotFoundError when no FormData ID was found.
func (fdq *FormDataQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = fdq.Limit(1).IDs(setContextOp(ctx, fdq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{formdata.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (fdq *FormDataQuery) FirstIDX(ctx context.Context) int {
	id, err := fdq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single FormData entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one FormData entity is found.
// Returns a *NotFoundError when no FormData entities are found.
func (fdq *FormDataQuery) Only(ctx context.Context) (*FormData, error) {
	nodes, err := fdq.Limit(2).All(setContextOp(ctx, fdq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{formdata.Label}
	default:
		return nil, &NotSingularError{formdata.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (fdq *FormDataQuery) OnlyX(ctx context.Context) *FormData {
	node, err := fdq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only FormData ID in the query.
// Returns a *NotSingularError when more than one FormData ID is found.
// Returns a *NotFoundError when no entities are found.
func (fdq *FormDataQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = fdq.Limit(2).IDs(setContextOp(ctx, fdq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{formdata.Label}
	default:
		err = &NotSingularError{formdata.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (fdq *FormDataQuery) OnlyIDX(ctx context.Context) int {
	id, err := fdq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of FormDataSlice.
func (fdq *FormDataQuery) All(ctx context.Context) ([]*FormData, error) {
	ctx = setContextOp(ctx, fdq.ctx, "All")
	if err := fdq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*FormData, *FormDataQuery]()
	return withInterceptors[[]*FormData](ctx, fdq, qr, fdq.inters)
}

// AllX is like All, but panics if an error occurs.
func (fdq *FormDataQuery) AllX(ctx context.Context) []*FormData {
	nodes, err := fdq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of FormData IDs.
func (fdq *FormDataQuery) IDs(ctx context.Context) (ids []int, err error) {
	if fdq.ctx.Unique == nil && fdq.path != nil {
		fdq.Unique(true)
	}
	ctx = setContextOp(ctx, fdq.ctx, "IDs")
	if err = fdq.Select(formdata.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (fdq *FormDataQuery) IDsX(ctx context.Context) []int {
	ids, err := fdq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (fdq *FormDataQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, fdq.ctx, "Count")
	if err := fdq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, fdq, querierCount[*FormDataQuery](), fdq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (fdq *FormDataQuery) CountX(ctx context.Context) int {
	count, err := fdq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (fdq *FormDataQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, fdq.ctx, "Exist")
	switch _, err := fdq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (fdq *FormDataQuery) ExistX(ctx context.Context) bool {
	exist, err := fdq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the FormDataQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (fdq *FormDataQuery) Clone() *FormDataQuery {
	if fdq == nil {
		return nil
	}
	return &FormDataQuery{
		config:     fdq.config,
		ctx:        fdq.ctx.Clone(),
		order:      append([]formdata.OrderOption{}, fdq.order...),
		inters:     append([]Interceptor{}, fdq.inters...),
		predicates: append([]predicate.FormData{}, fdq.predicates...),
		// clone intermediate query.
		sql:  fdq.sql.Clone(),
		path: fdq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.FormData.Query().
//		GroupBy(formdata.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (fdq *FormDataQuery) GroupBy(field string, fields ...string) *FormDataGroupBy {
	fdq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &FormDataGroupBy{build: fdq}
	grbuild.flds = &fdq.ctx.Fields
	grbuild.label = formdata.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.FormData.Query().
//		Select(formdata.FieldName).
//		Scan(ctx, &v)
func (fdq *FormDataQuery) Select(fields ...string) *FormDataSelect {
	fdq.ctx.Fields = append(fdq.ctx.Fields, fields...)
	sbuild := &FormDataSelect{FormDataQuery: fdq}
	sbuild.label = formdata.Label
	sbuild.flds, sbuild.scan = &fdq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a FormDataSelect configured with the given aggregations.
func (fdq *FormDataQuery) Aggregate(fns ...AggregateFunc) *FormDataSelect {
	return fdq.Select().Aggregate(fns...)
}

func (fdq *FormDataQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range fdq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, fdq); err != nil {
				return err
			}
		}
	}
	for _, f := range fdq.ctx.Fields {
		if !formdata.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if fdq.path != nil {
		prev, err := fdq.path(ctx)
		if err != nil {
			return err
		}
		fdq.sql = prev
	}
	return nil
}

func (fdq *FormDataQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*FormData, error) {
	var (
		nodes = []*FormData{}
		_spec = fdq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*FormData).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &FormData{config: fdq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, fdq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (fdq *FormDataQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := fdq.querySpec()
	_spec.Node.Columns = fdq.ctx.Fields
	if len(fdq.ctx.Fields) > 0 {
		_spec.Unique = fdq.ctx.Unique != nil && *fdq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, fdq.driver, _spec)
}

func (fdq *FormDataQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(formdata.Table, formdata.Columns, sqlgraph.NewFieldSpec(formdata.FieldID, field.TypeInt))
	_spec.From = fdq.sql
	if unique := fdq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if fdq.path != nil {
		_spec.Unique = true
	}
	if fields := fdq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, formdata.FieldID)
		for i := range fields {
			if fields[i] != formdata.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := fdq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := fdq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := fdq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := fdq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (fdq *FormDataQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(fdq.driver.Dialect())
	t1 := builder.Table(formdata.Table)
	columns := fdq.ctx.Fields
	if len(columns) == 0 {
		columns = formdata.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if fdq.sql != nil {
		selector = fdq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if fdq.ctx.Unique != nil && *fdq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range fdq.predicates {
		p(selector)
	}
	for _, p := range fdq.order {
		p(selector)
	}
	if offset := fdq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := fdq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// FormDataGroupBy is the group-by builder for FormData entities.
type FormDataGroupBy struct {
	selector
	build *FormDataQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (fdgb *FormDataGroupBy) Aggregate(fns ...AggregateFunc) *FormDataGroupBy {
	fdgb.fns = append(fdgb.fns, fns...)
	return fdgb
}

// Scan applies the selector query and scans the result into the given value.
func (fdgb *FormDataGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, fdgb.build.ctx, "GroupBy")
	if err := fdgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*FormDataQuery, *FormDataGroupBy](ctx, fdgb.build, fdgb, fdgb.build.inters, v)
}

func (fdgb *FormDataGroupBy) sqlScan(ctx context.Context, root *FormDataQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(fdgb.fns))
	for _, fn := range fdgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*fdgb.flds)+len(fdgb.fns))
		for _, f := range *fdgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*fdgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := fdgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// FormDataSelect is the builder for selecting fields of FormData entities.
type FormDataSelect struct {
	*FormDataQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (fds *FormDataSelect) Aggregate(fns ...AggregateFunc) *FormDataSelect {
	fds.fns = append(fds.fns, fns...)
	return fds
}

// Scan applies the selector query and scans the result into the given value.
func (fds *FormDataSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, fds.ctx, "Select")
	if err := fds.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*FormDataQuery, *FormDataSelect](ctx, fds.FormDataQuery, fds, fds.inters, v)
}

func (fds *FormDataSelect) sqlScan(ctx context.Context, root *FormDataQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(fds.fns))
	for _, fn := range fds.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*fds.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := fds.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
