// Code generated by ent, DO NOT EDIT.

package ent

import (
	"Portfolio/ent/formdata"
	"Portfolio/ent/predicate"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// FormDataDelete is the builder for deleting a FormData entity.
type FormDataDelete struct {
	config
	hooks    []Hook
	mutation *FormDataMutation
}

// Where appends a list predicates to the FormDataDelete builder.
func (fdd *FormDataDelete) Where(ps ...predicate.FormData) *FormDataDelete {
	fdd.mutation.Where(ps...)
	return fdd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (fdd *FormDataDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, fdd.sqlExec, fdd.mutation, fdd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (fdd *FormDataDelete) ExecX(ctx context.Context) int {
	n, err := fdd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (fdd *FormDataDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(formdata.Table, sqlgraph.NewFieldSpec(formdata.FieldID, field.TypeInt))
	if ps := fdd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, fdd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	fdd.mutation.done = true
	return affected, err
}

// FormDataDeleteOne is the builder for deleting a single FormData entity.
type FormDataDeleteOne struct {
	fdd *FormDataDelete
}

// Where appends a list predicates to the FormDataDelete builder.
func (fddo *FormDataDeleteOne) Where(ps ...predicate.FormData) *FormDataDeleteOne {
	fddo.fdd.mutation.Where(ps...)
	return fddo
}

// Exec executes the deletion query.
func (fddo *FormDataDeleteOne) Exec(ctx context.Context) error {
	n, err := fddo.fdd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{formdata.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (fddo *FormDataDeleteOne) ExecX(ctx context.Context) {
	if err := fddo.Exec(ctx); err != nil {
		panic(err)
	}
}
