// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// FormDataColumns holds the columns for the "Form Data" table.
	FormDataColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "email", Type: field.TypeString},
		{Name: "message", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime, Nullable: true},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true},
	}
	// FormDataTable holds the schema information for the "Form Data" table.
	FormDataTable = &schema.Table{
		Name:       "Form Data",
		Columns:    FormDataColumns,
		PrimaryKey: []*schema.Column{FormDataColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		FormDataTable,
	}
)

func init() {
	FormDataTable.Annotation = &entsql.Annotation{
		Table: "Form Data",
	}
}
